def expected_weekly_income (n):
   variable = int(input for i in range(6))
   G=sum(int,range(6)) 
   P=float(input("Number?"))
   B=(G*P)
   print(B) 

print("Enter hours worked on Monday") 
Mon=int(input("Number?")) 
print("Enter hours worked on Tuesday")
Tues=int(input("Number?"))
S=(Mon + Tues)
print("Enter hours worked on Wednesday")
Wed=int(input("Number?"))
T=(Wed+S)
print("Enter hours worked on Thursday")
Thurs=int(input("Number?"))
Q=(Thurs+T)
print("Enter hours worked on Friday")
Fri=int(input("Number?"))
R=(Fri+Q)
print("Enter hours worked Saturday")
Sat=int(input("Number?"))
F=(Sat+R)
print("Enter hours worked on Sunday")
Sun=int(input("Number?"))
G=(Sun+F)
print("Hours worked for the week",G)  
print("Rate of pay")
P=float(input("Number?"))
B=(G*P)
print(B) 